import importlib.util
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

from core.config import (
    DATABASE_AUTO_GENERATE_MIGRATIONS,
    DATABASE_AUTO_MIGRATE,
    SQLALCHEMY_DATABASE_URI,
)
from core.logging import logger

GOAL_FIRST_ANALYTICS_REVISION = "0013_goal_first_analytics"
BACKEND_DIR = Path(__file__).resolve().parents[2]
MIGRATIONS_DIR = BACKEND_DIR / "migrations"
GOAL_FIRST_ANALYTICS_MIGRATION = (
    MIGRATIONS_DIR
    / "versions"
    / "2026_08_28_0013_migrate_goal_first_analytics.py"
)

UNSAFE_AUTOGENERATED_OPERATIONS = (
    "op.drop_",
    "op.alter_column(",
    "op.execute(",
)


def run_database_migrations() -> bool:
    if not DATABASE_AUTO_MIGRATE:
        logger.info("Database migrations are disabled")
        return False

    alembic_config = _build_alembic_config()
    try:
        logger.info("Applying pending database migrations")
        command.upgrade(alembic_config, "head")

        if DATABASE_AUTO_GENERATE_MIGRATIONS:
            generated_revision = command.revision(
                alembic_config,
                message="auto schema update",
                autogenerate=True,
            )
            generated_revision_paths = _get_generated_revision_paths(generated_revision)
            if generated_revision_paths:
                _validate_generated_revisions_are_safe(generated_revision_paths)
                logger.info("Applying auto-generated database migration")
                command.upgrade(alembic_config, "head")
            else:
                logger.info("Database schema already matches SQLAlchemy models")

        return True
    except Exception as error:
        logger.exception("Database migration failed: %s", error)
        raise


def bootstrap_single_metric_analytics_defaults() -> bool:
    """Complete the goal-first defaults when migrations ran before a user existed.

    Alembic cannot create user-owned chart rows on a migrate-before-first-user
    installation.  The revision exposes a tightly scoped, idempotent repair
    that only runs after revision 0013 and when both catalog tables are empty.
    """

    from sqlalchemy import inspect, text

    from infrastructure.database.session import engine

    with engine.begin() as connection:
        inspector = inspect(connection)
        required_tables = {
            "alembic_version",
            "analytics_charts",
            "analytics_model_versions",
            "users",
        }
        if not all(inspector.has_table(table) for table in required_tables):
            return False
        current_revisions = set(
            connection.execute(
                text("SELECT version_num FROM alembic_version")
            ).scalars()
        )
        script = ScriptDirectory.from_config(_build_alembic_config())
        applied_revisions = {
            revision.revision
            for current in current_revisions
            for revision in script.iterate_revisions(current, "base")
        }
        if GOAL_FIRST_ANALYTICS_REVISION not in applied_revisions:
            return False
        has_catalog_rows = connection.execute(
            text(
                "SELECT EXISTS (SELECT 1 FROM analytics_model_versions) "
                "OR EXISTS (SELECT 1 FROM analytics_charts)"
            )
        ).scalar()
        if has_catalog_rows:
            return False

        spec = importlib.util.spec_from_file_location(
            "analytics_goal_first_bootstrap",
            GOAL_FIRST_ANALYTICS_MIGRATION,
        )
        if spec is None or spec.loader is None:
            raise RuntimeError("Unable to load the goal-first analytics migration")
        migration = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(migration)
        bootstrapped = bool(migration.bootstrap_empty_install(connection))
        if bootstrapped:
            logger.info("Bootstrapped the goal-first analytics catalog")
        return bootstrapped


def _build_alembic_config() -> Config:
    alembic_config = Config(str(BACKEND_DIR / "alembic.ini"))
    alembic_config.set_main_option("script_location", str(MIGRATIONS_DIR))
    alembic_config.set_main_option("sqlalchemy.url", SQLALCHEMY_DATABASE_URI)
    return alembic_config


def _get_generated_revision_paths(generated_revision: object) -> list[Path]:
    if generated_revision is None:
        return []

    revisions = (
        generated_revision
        if isinstance(generated_revision, list)
        else [generated_revision]
    )
    return [Path(revision.path) for revision in revisions if hasattr(revision, "path")]


def _validate_generated_revisions_are_safe(revision_paths: list[Path]) -> None:
    for revision_path in revision_paths:
        migration_text = revision_path.read_text()
        upgrade_text = _get_upgrade_body(migration_text)
        unsafe_operations = [
            operation
            for operation in UNSAFE_AUTOGENERATED_OPERATIONS
            if operation in upgrade_text
        ]
        if unsafe_operations:
            _delete_generated_revisions(revision_paths)
            raise RuntimeError(
                "Autogenerated migration contains operations that require manual "
                f"review: {', '.join(unsafe_operations)}"
            )


def _get_upgrade_body(migration_text: str) -> str:
    upgrade_marker = "def upgrade() -> None:"
    downgrade_marker = "def downgrade() -> None:"
    upgrade_start = migration_text.find(upgrade_marker)
    if upgrade_start == -1:
        return migration_text

    downgrade_start = migration_text.find(downgrade_marker, upgrade_start)
    if downgrade_start == -1:
        return migration_text[upgrade_start:]

    return migration_text[upgrade_start:downgrade_start]


def _delete_generated_revisions(revision_paths: list[Path]) -> None:
    for revision_path in revision_paths:
        revision_path.unlink(missing_ok=True)
