services:
  backend-sd:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-sd
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=sd
    ports:
      - "8000:8000"
    networks:
      - connex_network
    volumes:
      - sd-upload_tasks:/app/upload_tasks

  backend-wtctr:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-wtctr
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=wtctr
    ports:
      - "8001:8000"
    networks:
      - connex_network
    volumes:
      - wtctr-upload_tasks:/app/upload_tasks

volumes:
  sd-upload_tasks:
    driver: local
  wtctr-upload_tasks:
    driver: local

networks:
  connex_network:
    external: true