services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: connex_backend
    restart: unless-stopped
    environment:
      - FASTAPI_ROOT_PATH=/api
      - DATABASE_NAME=connex
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - connex_network
    volumes:
      - upload_tasks:/app/upload_tasks

volumes:
  upload_tasks:
    driver: local

networks:
  connex_network:
    external: true