services:
  wtctw-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wtctw_backend
    restart: unless-stopped
    environment:
      - FASTAPI_ROOT_PATH=/wtctw/api
      - DATABASE_NAME=wtctw
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - connex_network
    volumes:
      - wtctw_upload_tasks:/app/upload_tasks

volumes:
  wtctw_upload_tasks:
    driver: local

networks:
  connex_network:
    external: true