services:
  wtchk-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wtchkecls_backend
    restart: unless-stopped
    environment:
      - FASTAPI_ROOT_PATH=/wtchkecls/api
      - DATABASE_NAME=wtchkecls
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - connex_network
    volumes:
      - wtchk_upload_tasks:/app/upload_tasks

volumes:
  wtchk_upload_tasks:
    driver: local

networks:
  connex_network:
    external: true