#!/usr/bin/env python3
"""Generate the Cube deployment overlay and its persisted profile allocation.

The existing application compose file remains the source of truth for active
profiles. This generator deliberately uses only the Python standard library so
operators can validate a deployment without installing backend dependencies.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_COMPOSE = ROOT / "docker-compose.yml"
OUTPUT_COMPOSE = ROOT / "docker-compose.analytics.yml"
OUTPUT_MANIFEST = ROOT / "deploy" / "analytics" / "profiles.json"
SHARD_OVERRIDES = ROOT / "deploy" / "analytics" / "shard-overrides.json"
PROFILE_PATTERN = re.compile(r'^\s+profiles:\s*\["([a-z0-9_]+)"\]\s*$', re.MULTILINE)
CANARIES = frozenset({"wtchk_cls", "wtchk_ecls"})
SHARD_COUNT = 4
ROLLOUT_WAVE_SIZE = 10


def source_profiles() -> list[str]:
    profiles = sorted(set(PROFILE_PATTERN.findall(SOURCE_COMPOSE.read_text())))
    if not profiles:
        raise RuntimeError("No Compose profiles found in docker-compose.yml")
    missing_canaries = CANARIES.difference(profiles)
    if missing_canaries:
        raise RuntimeError(f"Missing required canaries: {sorted(missing_canaries)}")
    return profiles


def shard_overrides(profiles: list[str]) -> dict[str, int]:
    if not SHARD_OVERRIDES.exists():
        return {}
    overrides = json.loads(SHARD_OVERRIDES.read_text())
    if not isinstance(overrides, dict):
        raise RuntimeError("shard-overrides.json must contain an object")
    for profile, shard in overrides.items():
        if profile not in profiles:
            raise RuntimeError(f"Shard override names unknown profile {profile}")
        if not isinstance(shard, int) or not 1 <= shard <= SHARD_COUNT:
            raise RuntimeError(f"Shard override for {profile} must be 1-{SHARD_COUNT}")
    return overrides


def manifest_document(profiles: list[str]) -> dict:
    overrides = shard_overrides(profiles)
    non_canaries = [profile for profile in profiles if profile not in CANARIES]
    rollout_wave = {
        profile: index // ROLLOUT_WAVE_SIZE + 1
        for index, profile in enumerate(non_canaries)
    }
    return {
        "version": 1,
        "source": "docker-compose.yml",
        "allocation": "sorted profile names, round-robin across four shards",
        "shard_overrides": "deploy/analytics/shard-overrides.json",
        "rollout": "wtchk_cls and wtchk_ecls canaries, then sorted waves of ten",
        "profiles": [
            {
                "name": profile,
                "cube_store_shard": overrides.get(profile, index % SHARD_COUNT + 1),
                "rollout_wave": 0 if profile in CANARIES else rollout_wave[profile],
            }
            for index, profile in enumerate(profiles)
        ],
    }


def _profile_env_prefix(profile: str) -> str:
    return profile.upper()


def _service_suffix(profile: str) -> str:
    return profile.replace("_", "-")


def _yaml_list(values: list[str], indent: int) -> list[str]:
    prefix = " " * indent
    return [f"{prefix}- {value}" for value in values]


def compose_document(manifest: dict) -> str:
    entries = manifest["profiles"]
    profiles_by_shard = {
        shard: [
            entry["name"]
            for entry in entries
            if entry["cube_store_shard"] == shard
        ]
        for shard in range(1, SHARD_COUNT + 1)
    }
    lines = [
        "# GENERATED by scripts/generate_analytics_compose.py; do not edit by hand.",
        "# Use together with docker-compose.yml. No analytics service publishes a host port.",
        "",
        "x-cube-runtime: &cube-runtime",
        '  image: "cubejs/cube:v1.7.26@${CUBE_IMAGE_DIGEST:?Set a tested sha256 digest for Cube v1.7.26}"',
        "  restart: unless-stopped",
        "  read_only: true",
        "  init: true",
        "  security_opt:",
        "    - no-new-privileges:true",
        "  cap_drop:",
        "    - ALL",
        "  tmpfs:",
        "    - /tmp:rw,nosuid,nodev,noexec,size=128m,mode=1777",
        "  volumes:",
        "    - ./cube:/cube/conf:ro",
        "  logging:",
        "    driver: json-file",
        "    options:",
        '      max-size: "10m"',
        '      max-file: "10"',
        "",
        "x-cube-environment: &cube-environment",
        "  CUBEJS_DB_TYPE: postgres",
        "  CUBEJS_DB_HOST: postgres",
        '  CUBEJS_DB_PORT: "${ANALYTICS_DATABASE_PORT:-5432}"',
        '  CUBEJS_DB_SSL: "${ANALYTICS_DATABASE_SSL:-true}"',
        '  CUBEJS_DEV_MODE: "false"',
        '  CUBEJS_TELEMETRY: "false"',
        '  CUBEJS_JWT_AUDIENCE: "cube"',
        '  CUBEJS_JWT_ALGS: "HS256"',
        '  CUBEJS_ROLLUP_ONLY: "false"',
        '  CUBEJS_CACHE_AND_QUEUE_DRIVER: "cubestore"',
        '  CUBEJS_SCHEDULED_REFRESH_TIME_ZONES: "UTC"',
        '  CUBEJS_DB_QUERY_TIMEOUT: "${ANALYTICS_DB_QUERY_TIMEOUT_SECONDS:-300}"',
        "",
        "x-cubestore-runtime: &cubestore-runtime",
        '  image: "cubejs/cubestore:v1.7.26@${CUBESTORE_IMAGE_DIGEST:?Set a tested sha256 digest for Cube Store v1.7.26}"',
        '  platform: "${CUBESTORE_PLATFORM:-linux/amd64}"',
        "  restart: unless-stopped",
        "  init: true",
        "  security_opt:",
        "    - no-new-privileges:true",
        "  cap_drop:",
        "    - ALL",
        "  logging:",
        "    driver: json-file",
        "    options:",
        '      max-size: "10m"',
        '      max-file: "10"',
        "",
        "services:",
    ]

    for shard in range(1, SHARD_COUNT + 1):
        router = f"cubestore-router-shard-{shard}"
        workers = [
            f"cubestore-worker-{worker}-shard-{shard}" for worker in (1, 2)
        ]
        worker_addresses = ",".join(
            f"{worker}:1000{index}" for index, worker in enumerate(workers, 1)
        )
        lines.extend(
            [
                f"  {router}:",
                "    <<: *cubestore-runtime",
                "    profiles:",
                *_yaml_list(profiles_by_shard[shard], 6),
                "    networks:",
                f"      - analytics_store_shard_{shard}",
                "    environment:",
                f"      CUBESTORE_SERVER_NAME: {router}:9999",
                '      CUBESTORE_META_PORT: "9999"',
                f"      CUBESTORE_WORKERS: {worker_addresses}",
                f"      CUBESTORE_REMOTE_DIR: /cube/data/shard-{shard}",
                "      CUBESTORE_DATA_DIR: /cube/scratch",
                f'      ANALYTICS_AZURE_BLOB_PREFIX: "${{ANALYTICS_AZURE_BLOB_PREFIX_SHARD_{shard}:-clsense/cubestore/shard-{shard}}}"',
                "    volumes:",
                f"      - cubestore_shard_{shard}:/cube/data",
                f"      - cubestore_scratch_router_shard_{shard}:/cube/scratch",
                "",
            ]
        )
        for worker_index, worker in enumerate(workers, 1):
            lines.extend(
                [
                    f"  {worker}:",
                    "    <<: *cubestore-runtime",
                    "    profiles:",
                    *_yaml_list(profiles_by_shard[shard], 6),
                    "    networks:",
                    f"      - analytics_store_shard_{shard}",
                    "    environment:",
                    f"      CUBESTORE_SERVER_NAME: {worker}:1000{worker_index}",
                    f'      CUBESTORE_WORKER_PORT: "1000{worker_index}"',
                    f"      CUBESTORE_META_ADDR: {router}:9999",
                    f"      CUBESTORE_WORKERS: {worker_addresses}",
                    f"      CUBESTORE_REMOTE_DIR: /cube/data/shard-{shard}",
                    "      CUBESTORE_DATA_DIR: /cube/scratch",
                    f'      ANALYTICS_AZURE_BLOB_PREFIX: "${{ANALYTICS_AZURE_BLOB_PREFIX_SHARD_{shard}:-clsense/cubestore/shard-{shard}}}"',
                    "    volumes:",
                    f"      - cubestore_shard_{shard}:/cube/data",
                    f"      - cubestore_scratch_worker_{worker_index}_shard_{shard}:/cube/scratch",
                    "    depends_on:",
                    f"      - {router}",
                    "",
                ]
            )

    for entry in entries:
        profile = entry["name"]
        suffix = _service_suffix(profile)
        prefix = _profile_env_prefix(profile)
        router = f"cubestore-router-shard-{entry['cube_store_shard']}"
        shard_network = f"analytics_store_shard_{entry['cube_store_shard']}"
        backend = f"backend-{suffix}"
        common_environment = [
            "      <<: *cube-environment",
            f"      CUBEJS_DB_NAME: {profile}",
            f'      CUBEJS_DB_USER: "${{{prefix}_ANALYTICS_DB_USER:-}}"',
            f'      CUBEJS_DB_PASS: "${{{prefix}_ANALYTICS_DB_PASSWORD:-}}"',
            f'      CUBEJS_API_SECRET: "${{{prefix}_CUBE_API_SECRET:-}}"',
            f"      CUBEJS_CUBESTORE_HOST: {router}",
            f"      CUBEJS_APP_ID: clsense-{profile}",
            f"      CUBEJS_ORCHESTRATOR_ID: clsense-{profile}",
            f"      CUBEJS_PRE_AGGREGATIONS_SCHEMA: cube_preagg_{profile}",
            f"      ANALYTICS_PROFILE: {profile}",
            f"      ANALYTICS_METADATA_URL: http://{backend}:8000/internal/analytics/catalog",
            f'      ANALYTICS_METADATA_SECRET: "${{{prefix}_ANALYTICS_METADATA_SECRET:-}}"',
        ]
        lines.extend(
            [
                f"  {backend}:",
                f"    profiles: [{profile}]",
                "    environment:",
                f'      ANALYTICS_ENABLED: "${{{prefix}_ANALYTICS_ENABLED:-false}}"',
                f"      ANALYTICS_CUBE_API_URL: http://cube-api-{suffix}:4000",
                f'      ANALYTICS_CUBE_API_SECRET: "${{{prefix}_CUBE_API_SECRET:-}}"',
                f'      ANALYTICS_INTERNAL_METADATA_SECRET: "${{{prefix}_ANALYTICS_METADATA_SECRET:-}}"',
                "      ANALYTICS_EXPORT_DIR: /app/upload_tasks/analytics_exports",
                "    volumes:",
                f"      - {profile}_upload_tasks:/app/upload_tasks",
                "",
                f"  cube-api-{suffix}:",
                "    <<: *cube-runtime",
                f"    profiles: [{profile}]",
                "    networks:",
                "      - connex_network",
                f"      - {shard_network}",
                "    environment:",
                *common_environment,
                '      CUBEJS_REFRESH_WORKER: "false"',
                "    depends_on:",
                f"      - {router}",
                f"      - {backend}",
                "    healthcheck:",
                '      test: ["CMD", "node", "-e", "fetch(\'http://127.0.0.1:4000/readyz\').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]',
                "      interval: 30s",
                "      timeout: 5s",
                "      retries: 5",
                "      start_period: 60s",
                "",
                f"  cube-refresh-{suffix}:",
                "    <<: *cube-runtime",
                f"    profiles: [{profile}]",
                "    networks:",
                "      - connex_network",
                f"      - {shard_network}",
                "    environment:",
                *common_environment,
                '      CUBEJS_REFRESH_WORKER: "true"',
                "    depends_on:",
                f"      - {router}",
                f"      - {backend}",
                "",
            ]
        )

    lines.extend(
        [
            "networks:",
            "  connex_network:",
            "    external: true",
            "    name: connex_network",
            *[
                line
                for shard in range(1, SHARD_COUNT + 1)
                for line in (
                    f"  analytics_store_shard_{shard}:",
                    "    internal: true",
                )
            ],
            "",
            "volumes:",
            *[f"  cubestore_shard_{shard}:" for shard in range(1, SHARD_COUNT + 1)],
            *[
                f"  cubestore_scratch_{node}_shard_{shard}:"
                for shard in range(1, SHARD_COUNT + 1)
                for node in ("router", "worker_1", "worker_2")
            ],
            "",
        ]
    )
    return "\n".join(lines)


def _check_file(path: Path, expected: str) -> bool:
    actual = path.read_text() if path.exists() else ""
    if actual == expected:
        return True
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path),
        tofile=f"generated:{path}",
        lineterm="",
    )
    print("\n".join(diff), file=sys.stderr)
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if checked-in generated files differ from source compose",
    )
    args = parser.parse_args()

    manifest = manifest_document(source_profiles())
    manifest_text = json.dumps(manifest, indent=2) + "\n"
    compose_text = compose_document(manifest)

    if args.check:
        current = _check_file(OUTPUT_MANIFEST, manifest_text)
        current = _check_file(OUTPUT_COMPOSE, compose_text) and current
        return 0 if current else 1

    OUTPUT_MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MANIFEST.write_text(manifest_text)
    OUTPUT_COMPOSE.write_text(compose_text)
    print(f"generated {OUTPUT_MANIFEST.relative_to(ROOT)} ({len(manifest['profiles'])} profiles)")
    print(f"generated {OUTPUT_COMPOSE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
