name: WTCHK CLSense Backend UAT Pipeline

on:
  push:
    branches:
      - wtchk-uat
    paths:
      - backend/**
      - requirements.txt
      - Dockerfile
      - .github/workflows/pipeline-wtchk-uat.yml

env:
  DOCKERHUB_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/clsense-wtchk-backend-uat

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build . \
            --pull \
            -t ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }} \
            -t ${{ env.DOCKERHUB_IMAGE_NAME }}:uat-latest

      - name: Push to DockerHub
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:uat-latest