name: ECLS CLSense Backend Dev Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - backend/**
      - requirements.txt
      - Dockerfile
      - .github/workflows/pipeline-ecls-dev.yml

env:
  DOCKERHUB_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/clsense-ecls-backend-dev
  IS_ECLS_ENABLED: true
jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build ./backend \
            --pull \
            --build-arg IS_ECLS_ENABLED=${{ env.IS_ECLS_ENABLED }} \
            -t ${{ env.DOCKERHUB_IMAGE_NAME }}:latest

      - name: Push to DockerHub
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:latest